# Generated by Django 4.2.5 on 2023-09-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_logo', models.ImageField(upload_to='logos/')),
                ('light_logo', models.ImageField(upload_to='logos/')),
                ('text', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=455)),
                ('copyright', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeaderLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_logo', models.ImageField(upload_to='logos/')),
                ('light_logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='OneHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(default='#', max_length=755)),
                ('is_submenu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RightButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('description', models.TextField()),
                ('favicon', models.FileField(upload_to='favicon')),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('link', models.CharField(default='#', max_length=755)),
            ],
        ),
        migrations.CreateModel(
            name='TopHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwoHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(default='#', max_length=755)),
                ('is_submenu', models.BooleanField(default=False)),
                ('one_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components_app.oneheader')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(default='#', max_length=755)),
                ('one_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components_app.oneheader')),
                ('two_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components_app.twoheader')),
            ],
        ),
    ]
