# Generated by Django 4.2.5 on 2023-09-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0002_footerlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name_plural': 'Footer Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='footerlinks',
            options={'verbose_name_plural': 'Footer Linklar'},
        ),
        migrations.AlterModelOptions(
            name='headerlogo',
            options={'verbose_name_plural': 'Header Logo Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='oneheader',
            options={'verbose_name_plural': '1-Darajali Menyular'},
        ),
        migrations.AlterModelOptions(
            name='rightbutton',
            options={'verbose_name_plural': "O'ng Tomon Tugmacha"},
        ),
        migrations.AlterModelOptions(
            name='seosettings',
            options={'verbose_name_plural': 'Seo Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name_plural': 'Ijtimoiy Tarmoqlar'},
        ),
        migrations.AlterModelOptions(
            name='threeheader',
            options={'verbose_name_plural': '3-Darajali Menyular'},
        ),
        migrations.AlterModelOptions(
            name='topheader',
            options={'verbose_name_plural': 'Top Header Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='twoheader',
            options={'verbose_name_plural': '2-Darajali Menyular'},
        ),
    ]
