# Generated by Django 4.2.5 on 2023-09-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0003_alter_footerinfo_options_alter_footerlinks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='copyright_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='copyright_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='copyright_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='location_en',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='location_ru',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='location_uz',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footerlinks',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerlinks',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footerlinks',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oneheader',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oneheader',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oneheader',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rightbutton',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rightbutton',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rightbutton',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='keywords_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='keywords_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='keywords_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='title_en',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='title_ru',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='title_uz',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='threeheader',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threeheader',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threeheader',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twoheader',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twoheader',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twoheader',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
