# Generated by Django 4.2.5 on 2023-11-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0004_footerinfo_copyright_en_footerinfo_copyright_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerlogo',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
