# Generated by Django 4.2.5 on 2023-11-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0005_headerlogo_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qidirish_1', models.CharField(max_length=255)),
                ('qidirish_2', models.CharField(max_length=255)),
            ],
        ),
    ]
