# Generated by Django 4.2.5 on 2023-11-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0007_alter_moretexts_options_moretexts_qidirish_1_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='slider_text',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
