# Generated by Django 4.2.5 on 2023-11-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0008_moretexts_slider_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='slider_text_en',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='slider_text_ru',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='slider_text_uz',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
