# Generated by Django 4.2.5 on 2023-11-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0009_moretexts_slider_text_en_moretexts_slider_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='news_cap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='news_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
