# Generated by Django 4.2.5 on 2023-11-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0011_moretexts_news_cap_en_moretexts_news_cap_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='news_more',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='news_more_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='news_more_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='news_more_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
