# Generated by Django 4.2.5 on 2023-11-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0012_moretexts_news_more_moretexts_news_more_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='elon_cap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_more',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
