# Generated by Django 4.2.5 on 2023-11-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0013_moretexts_elon_cap_moretexts_elon_more_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='elon_cap_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_cap_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_cap_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_more_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_more_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_more_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='elon_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
