# Generated by Django 4.2.5 on 2023-11-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0014_moretexts_elon_cap_en_moretexts_elon_cap_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_cap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_cap_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_cap_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_cap_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
