# Generated by Django 4.2.5 on 2023-11-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0015_moretexts_talim_yonalishlari_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_barcha_yonalishlar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_barcha_yonalishlar_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_barcha_yonalishlar_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_barcha_yonalishlar_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_more_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_more_link_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_more_link_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='talim_yonalishlari_more_link_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
