# Generated by Django 4.2.5 on 2023-11-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0018_moretexts_video_cap_moretexts_video_cap_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='interaktiv_hizmatlar_cap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='interaktiv_hizmatlar_cap_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='interaktiv_hizmatlar_cap_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='interaktiv_hizmatlar_cap_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='interaktiv_hizmatlar_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='interaktiv_hizmatlar_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='interaktiv_hizmatlar_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='interaktiv_hizmatlar_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
