# Generated by Django 4.2.5 on 2023-11-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0019_moretexts_interaktiv_hizmatlar_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='hamkorlar_cap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='hamkorlar_cap_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='hamkorlar_cap_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='hamkorlar_cap_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='hamkorlar_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='hamkorlar_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='hamkorlar_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='hamkorlar_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
