# Generated by Django 4.2.5 on 2023-11-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0022_moretexts_news_korishlar_soni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='bosh_sahifa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='bosh_sahifa_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='bosh_sahifa_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='bosh_sahifa_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
