# Generated by Django 4.2.5 on 2023-11-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0023_moretexts_bosh_sahifa_moretexts_bosh_sahifa_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='qaynoq_yangiliklar_cap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='qaynoq_yangiliklar_cap_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='qaynoq_yangiliklar_cap_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='qaynoq_yangiliklar_cap_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='qaynoq_yangiliklar_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='qaynoq_yangiliklar_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='qaynoq_yangiliklar_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='qaynoq_yangiliklar_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
