# Generated by Django 4.2.5 on 2023-11-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0024_moretexts_qaynoq_yangiliklar_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='barcha_yangiliklar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='barcha_yangiliklar_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='barcha_yangiliklar_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='barcha_yangiliklar_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
