# Generated by Django 4.2.5 on 2023-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0025_moretexts_barcha_yangiliklar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='ta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='ta_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='ta_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='ta_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
