# Generated by Django 4.2.5 on 2023-11-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0026_moretexts_ta_moretexts_ta_en_moretexts_ta_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='yangiliklar_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='yangiliklar_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='yangiliklar_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='yangiliklar_text_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
