# Generated by Django 4.2.5 on 2023-11-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components_app', '0027_moretexts_yangiliklar_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexts',
            name='kop_korilgan_yangiliklar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='kop_korilgan_yangiliklar_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='kop_korilgan_yangiliklar_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='kop_korilgan_yangiliklar_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='oxirgi_yangiliklar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='oxirgi_yangiliklar_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='oxirgi_yangiliklar_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moretexts',
            name='oxirgi_yangiliklar_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
