# Generated by Django 4.2.5 on 2023-09-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
