# Generated by Django 4.2.5 on 2023-11-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_category_title_en_category_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='elon_sifatida_belgilash',
            field=models.BooleanField(default=False),
        ),
    ]
