# Generated by Django 4.2.5 on 2023-11-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_news_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
