# Generated by Django 4.2.5 on 2023-11-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_cap',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_cap_en',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_cap_ru',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_cap_uz',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
