# Generated by Django 4.2.5 on 2023-11-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_hitcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
