# Generated by Django 4.2.5 on 2023-09-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='counter/')),
                ('count', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('is_aniq', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hamkorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hamkorlar')),
                ('title', models.CharField(max_length=255)),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_image', models.ImageField(upload_to='home-images/')),
                ('two_image', models.ImageField(upload_to='home-images/')),
                ('three_image', models.ImageField(upload_to='home-images/')),
                ('cap', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAboutQulayliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InteraktivHizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interaktiv-hizmatlar')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rahbariyat/')),
                ('name', models.CharField(max_length=455)),
                ('lavozimi', models.TextField()),
                ('qabul', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sliders/')),
            ],
        ),
        migrations.CreateModel(
            name='TalimYonalishlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talim-yonalishlari/')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='videos')),
                ('link', models.TextField()),
            ],
        ),
    ]
