# Generated by Django 4.2.5 on 2023-09-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name_plural': 'Counter'},
        ),
        migrations.AlterModelOptions(
            name='hamkorlar',
            options={'verbose_name_plural': 'Hamkorlar'},
        ),
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name_plural': 'Asosiy Menyu About'},
        ),
        migrations.AlterModelOptions(
            name='homeaboutqulayliklar',
            options={'verbose_name_plural': 'Home About Qulayliklar'},
        ),
        migrations.AlterModelOptions(
            name='interaktivhizmatlar',
            options={'verbose_name_plural': 'Interaktiv Hizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='rahbariyat',
            options={'verbose_name_plural': 'Rahbariyat'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Slayderlar'},
        ),
        migrations.AlterModelOptions(
            name='talimyonalishlari',
            options={'verbose_name_plural': "Talim Yo'nalishlari"},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Video'},
        ),
    ]
