# Generated by Django 4.2.5 on 2023-09-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_counter_options_alter_hamkorlar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hamkorlar',
            name='button_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hamkorlar',
            name='button_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hamkorlar',
            name='button_title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hamkorlar',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hamkorlar',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hamkorlar',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='button_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='button_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='button_title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='cap_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='cap_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='cap_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutqulayliklar',
            name='body_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutqulayliklar',
            name='body_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutqulayliklar',
            name='body_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutqulayliklar',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutqulayliklar',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutqulayliklar',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaktivhizmatlar',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interaktivhizmatlar',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interaktivhizmatlar',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interaktivhizmatlar',
            name='button_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaktivhizmatlar',
            name='button_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaktivhizmatlar',
            name='button_title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaktivhizmatlar',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaktivhizmatlar',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaktivhizmatlar',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='lavozimi_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='lavozimi_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='lavozimi_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='name_en',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='name_ru',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='name_uz',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='qabul_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='qabul_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='qabul_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='cap_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='cap_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='cap_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='talimyonalishlari',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='talimyonalishlari',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='talimyonalishlari',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='talimyonalishlari',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='talimyonalishlari',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='talimyonalishlari',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
