# Generated by Django 4.2.5 on 2023-11-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_counter_title_en_counter_title_ru_counter_title_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Slayderlar'},
        ),
    ]
