# Generated by Django 4.2.5 on 2023-11-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_slider_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='talimyonalishlari',
            name='link',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
