# Generated by Django 4.2.5 on 2023-11-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_talimyonalishlari_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('width', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Xarita Sozlamalari',
            },
        ),
    ]
