# Generated by Django 4.2.5 on 2023-09-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Sahifalar'},
        ),
        migrations.AddField(
            model_name='page',
            name='full_page',
            field=models.BooleanField(default=False),
        ),
    ]
