# Generated by Django 4.2.5 on 2023-11-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0003_page_body_en_page_body_ru_page_body_uz_page_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title_cap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
