# Generated by Django 4.2.5 on 2023-11-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0004_page_title_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title_cap_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_cap_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_cap_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
